### ISSUE TITLE
09 Residual Categories codes added to Ethnicity code set

### ISSUE THREAD

**Issue by melissafordyce** [new-zealand-research-information-system/nzris-codesets#8]
The 09 Residual Categories codes have now been added to the Ethnicity code set (as per attached).

@chrisdangerfield can you please add this to the appropriate branch.

[ethnicity-new-zealand-standard-classification.xlsx](https://github.com/new-zealand-research-information-system/nzris-codesets/files/3650129/ethnicity-new-zealand-standard-classification.xlsx)

**Comment by chrisdangerfield** [comment]
Updated in master branch
