### ISSUE TITLE
ISO 4217 Currency Codes now include both alpha and numeric codes

### ISSUE THREAD

**Issue by melissafordyce** [new-zealand-research-information-system/nzris-codesets#9]
ISO 4217 Currency Codes now include both alpha and numeric codes (attached).

@chrisdangerfield can you please add to the appropriate branch.

[currency-codes-iso-4217.xlsx](https://github.com/new-zealand-research-information-system/nzris-codesets/files/3650132/currency-codes-iso-4217.xlsx)

**Comment by chrisdangerfield** [comment]
Updated in master branch
